version: 2

jobs:
  build:
    machine: true
    working_directory: ~/mobile-devops
    steps:
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: sudo rm -f /etc/boto.cfg
      - run: echo $GCLOUD_SERVICE_KEY | sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=-
      - run: echo 'soe' > some.sh && sudo /opt/google-cloud-sdk/bin/gcloud config list
      - run: sudo gsutil -h Cache-Control:"Cache-Control:private, max-age=0, no-transform" \cp some.sh gs://staging.myjobscorner.com/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
